In [1]:
import numpy as np

In [20]:
# we will start with two arrays
a = np.array([
    [21, 42, 32],
    [1, -129.2, 234.0],
    [3, 6, 9]
])
# make an array of zeros
b = np.zeros((3,3)) 
display(a)
display(b)


array([[  21. ,   42. ,   32. ],
       [   1. , -129.2,  234. ],
       [   3. ,    6. ,    9. ]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# notice that arrays are forced
# to be all the same data type
display(a.dtype, b.dtype)

dtype('float64')

dtype('float64')

In [35]:
# we can do elementwise math
display(b + 1)
display(a / 100)
display((b + 1) + a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[ 0.21 ,  0.42 ,  0.32 ],
       [ 0.01 , -1.292,  2.34 ],
       [ 0.03 ,  0.06 ,  0.09 ]])

array([[  22. ,   43. ,   33. ],
       [   2. , -128.2,  235. ],
       [   4. ,    7. ,   10. ]])

In [34]:
# we can do linear algebra calculations like determinants
# inverse matrices or solvers
display(np.linalg.det(a))
display(np.linalg.inv(a))
display(a @ np.linalg.inv(a)) # to prove it is the inverse

# get the first column of b+1
display(np.linalg.solve(a, (b + 1)[:,1])) 

-12201.60000000001

array([[ 0.21036585,  0.0152439 , -1.14430894],
       [-0.05679583, -0.00762195,  0.40011146],
       [-0.03225806,  0.        ,  0.22580645]])

array([[ 1.0000000e+00,  0.0000000e+00, -8.8817842e-16],
       [ 8.8817842e-16,  1.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00, -6.9388939e-18,  1.0000000e+00]])

array([-0.91869919,  0.33569368,  0.19354839])